import Head from 'next/head'
import Image from 'next/image'
import Avatar from '../components/Avatar'
import { MicrophoneIcon, ViewGridIcon } from "@heroicons/react/solid"
import { SearchIcon } from "@heroicons/react/outline"
import Footer from '../components/Footer'
import { useRef } from "react"
import { useRouter } from "next/router"

export default function Home() {
  const searchInputRef = useRef(null);
  const router = useRouter();

  // if term exists, push search input onto the router stack
  const search = (e) => {
    e.preventDefault();
    const term = searchInputRef.current.value;

    if (!term) {
      return;
    }
    router.push(`/search?term=${term}`);
  }

  return (
    <div className='flex flex-col items-center justify-center h-screen'>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <header className='flex w-full p-5 justify-between text-sm text-gray-700'>
        {/* Left */}
        <div className='flex space-x-4 items-center'>
          <p className='link'>About</p>
          <p className='link'>Store</p>
        </div>

        {/* Right */}
        <div className='flex space-x-4 items-center'>
          <p className='link'>Gmail</p>
          <p className='link'>Images</p>

          {/* Icon */}
          <ViewGridIcon className='h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer'/>

          {/* Avatar */}
          <Avatar url='https://lh3.googleusercontent.com/3NHoBFpjpRzkqEp4Ollu1cgjcvh_3BwhfKTlV85SwJlFgLH7bvxJRseDCDiHXKcL' />
        </div>
      </header>

      {/* Body */}
      <form className='flex flex-col items-center mt-35 flex-grow w-4/5'>
        
        {/* google image */}
        <Image 
          loading='lazy'
          src='https://play-lh.googleusercontent.com/1-hPxafOxdYpYZEOKzNIkSP43HXCNftVJVttoo4ucl7rsMASXW3Xr6GlXURCubE1tA=w3840-h2160-rw'
          height={100}
          width={350}
          alt=''
        />

        {/* input field and search/microphone icons */}
        <div className='flex w-full hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border
          px-5 py-3 items-center sm:max-w-xl lg:max-w-2xl'>
          <SearchIcon className='h-5 mr-3 text-gray-500'/>
          <input ref={searchInputRef} type='text' className='flex-grow focus:outline-none'/>
          <MicrophoneIcon className='h-5 '/>
        </div>

        {/* google search button and "im feeling luck" button */}
        <div className='flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:space-y-0 sm:flex-row sm:space-x-4'>
          <button onClick={search} className='btn'>Google Search</button>
          <button onClick={search} className='btn'>I&apos;m Feeling Lucky</button>
        </div>
      </form>

      {/* Footer */}
      <Footer />
    </div>
  )
}
